export const services = [
    "Haircuts and trims",
    "Haircuts with clippers",
    "Formal hairstyles",
    "Basic hairstyles",
    "Shaves",
    "Custom shave designs",
    "Braids",
    "Facial hair grooming, cutting, and styling",
    "Colors and highlights",
    "Basic manicures",
    "Single-process color",
    "Double-process color",
    "Highlights (cap or foil)",
    "Straightening treatments",
    "Perms",
    "Relaxers",
    "Hair extensions",
    "Blowouts",
    "Waxing",
    "Makeup application",
    "Tanning",
    "Spray tanning",
    "Manicures",
    "Pedicures",
    "Acrylic nail and tip application",
    "Massage",
    "Facials",
    "Skincare consultation",
    "Lash extensions",
    "Electrolysis hair removal",
    "Fillers and injections",
  ];